#!/usr/bin/env bash
# Configure domain zone so that the subdomain www points to your load-balancer IP
if [[ $# -lt 1 || $# -gt 2 ]]; then
	echo "Usage: $0 domain [subdomain]"
	exit 1
fi

find_info() {
    if [[ -z $subdomain ]]; then
        subslst=("www" "lb-01" "web-01" "web-02");
    else
        subslst=("$subdomain");
    fi

    for sub in "${subslst[@]}"
    do
      type=$(dig +noall +answer $sub.$domain | awk '{print $4}');
      IP=$(dig +noall +answer $sub.$domain | awk '{print $5}');
      echo "The subdomain $sub is a $type record and points to $IP"
    done
}

domain=$1
subdomain=$2
find_info "domain" "subdomain"

exit 0
