#!/usr/bin/env bash
# Transfer a file to your server

# Check if correct number of arguments are provided
if [ "$#" -lt 4 ]; then
    usage
fi

ssh -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2:~/"
