#!/usr/bin/env bash
# Installs nginx and route GET to a web page
sudo apt update
sudo apt install nginx -y
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start
