#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
sudo apt update
sudo apt install nginx -y
echo 'Hello World!' > /var/www/html/index.html
sudo sed -i 's@try_files $uri $uri/ =404;@return 301 / https://www.youtube.com/watch?v=QH2-TGUlwu4;@g' /etc/nginx/sites-available/default
service nginx start
