#!/usr/bin/env bash
# Adds header to each server
sudo apt update
sudo apt install nginx -y
echo 'Hello World!' > /var/www/html/index.html
sudo sed -i 's|server_name _;|add_header X-Served-By;\n\n\tserver_name _;\n|g' /etc/nginx/sites-available/default
sudo service nginx reload
