#!/usr/bin/env bash
# Fizz Buzz challenge from 1 to 100
for i in {1..100..1}
do
	if [ $((i % 15)) -eq 0 ]
	then
		echo "FizzBuzz"
	elif [ $((i % 3)) -eq 0 ]
	then
		echo "Fizz"
	elif [ $((i % 5)) -eq 0 ]
	then
		echo "Buzz"
	else
		echo "$i"
	fi
done
