#!/usr/bin/env bash
# Prints Best School
# Prints an extra Hi on the 9th iteration
counter=0
while [ $counter -lt 10 ]
do
	echo "Best School"
	if [ $counter -eq 8 ]
	then
		echo "Hi"
	fi
	(( counter++ ))
done
