#!/usr/bin/env bash
# Loops from 1 to 10 printing the numbers
# Special message if num is 4 or 8
for i in {1..10..1}
do
	if [ "$i" -eq 4 ]
	then
		echo "bad luck"
	elif [ "$i" -eq 8 ]
	then
		echo "bad luck"
	else
		echo "Best School"
	fi
done
