#!/usr/bin/env bash
# Loops from 1 to 20 and prints out a different message
# if the number is 4, 9, 17
counter=1
while [ $counter -le 20 ]
do
	echo "$counter"

	case $counter in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	(( counter++ ))
done
