#!/usr/bin/env bash
# Prints every minute to 12:59
i=0
echo "Hour: $i"
while [ "$i" -le 12 ]
do
	min=1
	while [ "$min" -le 59 ]
	do
		echo "$min"
		(( min++ ))
	done
	(( i++ ))
	if [ "$i" -le 12 ]
	then
		echo "Hour: $i"
	fi
done
