#!/usr/bin/env bash
# Prints every minute to 12:59
i=0
echo "Hour: $i"
while [ "$i" -le 13 ]
do
	for min in {1..59..1}
	do
		echo "$min"
	done
	(( i++ ))
	if [ "$i" -lt 13 ]
	then
		echo "Hour: $i"
	fi
done
