#!/usr/bin/env bash
# Local host resolves to 127.0.0.2
# Facebook resolves to 8.8.8.8

echo "127.0.0.2	localhost" > ~/hosts.new
echo "::2     ip6-localhost ip6-loopback" >> ~/hosts.new
echo "8.8.8.8	facebook.com" >> ~/hosts.new

cp ~/hosts.new /etc/hosts
