#!/usr/bin/env bash
# Curling port 80 return a page that contains Hello Holberton
sudo apt-get update -y
sudo apt-get install apache2
sudo /etc/init.d/apache2 start
echo 'Hello Holberton' | sudo tee -a /var/www/html/index.html
sudo /etc/init.d/apache2 restart
