#!/usr/bin/env bash
# Creating user to improve security by not using root
sudo adduser nginx
sudo sed -i 's|user www-data;|user nginx;|g' /etc/nginx/nginx.conf
sudo sed -i 's|server {|server {\n\tlisten *:80;|g' /etc/nginx/nginx.conf
sudo service nginx restart
