#!/usr/bin/env bash
# Uses ssh to connect to your server using the private key ~/.ssh/school with the user ubuntu.
cat ~/.ssh/school | ssh ubuntu@server01 "mkdir -p ~/.ssh && cat >> ~/.ssh/authorized_keys"
ssh -A server01
ssh ubuntu@server01
